### PR TITLE
Support for ProxyURL

### PR DESCRIPTION
**Pull request by Jvekka**
Added option for ProxyURL as MMA supports it.
It hasn't been tested yet, but I'll confirm here later if everything were Ok with.

### CODE REVIEW

**Comment by flcdrg** [comment]
No worries. Let me know when you've tried it out

**Comment by flcdrg** [comment]
@Jvekka did you get a chance to test this?

**Comment by Jvekka** [comment]
Hi,

Sorry for the late response. I've been testing it and going through the documentation. I made small changes so there is space between items, but it seems that the installer doesn't support 'OPINSIGHTS_PROXY_URL'. It can be used with setup.exe but not with the MMASetup-*.exe.

This pull request can be removed as it would require more work with the package and the installation mechanism.

If someone is looking at a method to modify or add the proxy to MMA, there is two options (at least):
1. Extract the package and run setup.exe with required params
2. Install the package with (or without workspace details) and modify it directly from the command line using the following guide: https://kevinholman.com/2017/08/16/adding-direct-agent-oms-workspace-and-proxy-via-powershell/

**Comment by flcdrg** [comment]
No worries, thanks for getting back to me.

**Pull request closed without merging**
